### ISSUE TITLE
DynamicIP implementation

### ISSUE THREAD

**Issue by moom0o** [TCPShield/RealIP#11]
Hello, I made this plugin (https://github.com/moom0o/TCPShieldDynamicIP) that when the server starts, it will update the ip on tcpshield's website. It would be nice if this was an official feature of the plugin, and if there was an easier way of getting a token for use with the api.

**Comment by paulzhng** [comment]
Hi,

we currently do not plan to add this feature as most of our users do not have IPs which change dynamically. We recommend using services like DynDNS and setting the backend in our panel configuration to the domain.
