### ISSUE TITLE
The plugin wont work

### ISSUE THREAD

**Issue by BurntRanch** [TCPShield/RealIP#12]
i installed the plugin properly, started my server, and soon enough, The plugin can't load! i tried upgrading from 1.8 to 1.16.1 and it doesn't help! Here is a screenshot of what happens, please help me.
![image](https://user-images.githubusercontent.com/69512353/89898392-4fbef900-dbe9-11ea-8014-da127c88079a.png)
(server details:
software: spigot
version: 1.16.1)

**Comment by paulzhng** [comment]
Please install ProtocolLib and try again.

**Comment by BurntRanch** [comment]
Oh it works! Thank you! I couldn't respond because i was busy.
