### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by BurntRanch** [TCPShield/RealIP#14]
Greetings, Recently i have been thinking "Hm, let me build and setup my server!" I started the server, Connected from the domain, got hit with a disconnect, tried to connect from the Raw IP and it wont work, neither does localhost, When i disabled TCPShield i was able to logon, im on windows and whenever i logon it says disconnected or connection refused. Please contain an email so i can send you where im from (like for example canada).

Technical information:
Windows version: 8.1
Server version: Multiple versions (1.8 - 1.16)
Server port: default (25565)
VPN: Not using
RAM: (dont be surprised but) 2 GBs
![image](https://user-images.githubusercontent.com/69512353/91307793-14aaf100-e7b7-11ea-80d3-d2ac5ab5b9dd.png)
(when i connect to the domain)
![image](https://user-images.githubusercontent.com/69512353/91307838-242a3a00-e7b7-11ea-9b1f-774aa9fb5b99.png)
(when i connect to localhost)
![image](https://user-images.githubusercontent.com/69512353/91307986-53d94200-e7b7-11ea-8a5e-12e93f0b4a71.png)
(when i connect to the raw IP)

**Comment by JosiahWhite** [comment]
This is likely a configuration issue with your DNS or TCPShield panel. Please open a support ticket on our discord here: https://discord.com/invite/XKU9UpV

**Comment by BurntRanch** [comment]
Oh alright, i will.
