### ISSUE TITLE
Issue with velocity it works but...

### ISSUE THREAD

**Issue by johncsuti** [TCPShield/RealIP#15]
Velocity version 1.0.9
It seems to throw this error not sure what is causing it or how to fix it.
https://mclo.gs/0InVzeY
(Pasted via mclo.gs do to it being rather long.

**Comment by paulzhng** [comment]
Fixed; see https://github.com/TCPShield/RealIP/commit/32142f99611124f0d81cc9d8d76ab0d2ab073278
Release available at https://github.com/TCPShield/RealIP/releases/tag/v2.3
