### ISSUE TITLE
Geyser support

### ISSUE THREAD

**Issue by bobhenl** [TCPShield/RealIP#17]
Hi, could you add some way to support Geyser plugin? With using TCPShield it doesn't work.... try look here too https://github.com/GeyserMC/Geyser/wiki/FAQ.

**Comment by toinouH** [comment]
So for a support of Geyser we need the option to open udp ports because Minecraft Bedrock Edition works with UDP and not tcp.
Thank you for reading.

**Comment by bobhenl** [comment]
And would it be possible?

**Comment by JosiahWhite** [comment]
This is something we are actively working on supporting. For news and more information, feel free to join our discord here: https://discord.com/invite/XKU9UpV
