### ISSUE TITLE
Different UUID, possible conversion

### ISSUE THREAD

**Issue by ShayBox** [TCPShield/RealIP#19]
After setting up TCPShield and installing the plugin, players have UUIDs that are not their actual UUID, I'm not sure if this is supposed to happen or not, but if it is, a possible way to look up usernames for their real UUID when they join and convert existing playerdata to their new UUID would be useful, right now everyone has been reset until I can manually rename the playerdata file.

EDIT: I found the discord, I'll use that for my support request and leave this for this feature suggestion.

**Comment by ghost** [comment]
Hello, it looks like we resolved this over Discord.

Thanks, (For those in the future, he had his server in offline mode so UUIDs changed)
