### ISSUE TITLE
Velocity 1.1.0

### ISSUE THREAD

**Issue by katekerllenevich** [TCPShield/RealIP#22]
Velocity has been updated to 1.1.0 and I am requesting you update your plugin from 1.0.0 to 1.1.0. Thanks!

**Comment by paulzhng** [comment]
Our plugin should work fine with the newest version of Velocity. Are there any errors?

**Comment by katekerllenevich** [comment]
No, but the documentation has not been updated for this so I just assumed. Sorry!
