### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by Obydux** [TCPShield/RealIP#25]
Would be cool if you guys made a server-side Fabric mod version of this plugins

**Comment by paulzhng** [comment]
Adding support for a new platform poses many challenges, including but not limited to the initial development and active maintenance of that platform. I personally consider Fabric as a server platform still too niche and thus deem active support not worth the effort.

A solution for you would be to use BungeeCord in front of your Fabric server and running our plugin on the BungeeCord. 

Should the demand for Fabric rise, I'd be happy to look further into supporting it natively.
