### ISSUE TITLE
Java 11 - Illegal Reflection Access Operations

### ISSUE THREAD

**Issue by TASelwyn** [TCPShield/RealIP#30]
TCPShield v2.4 seems to be executing illegal reflection access operations on java 11.

The server is running Java 11

`openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)`

The following error shows up. Just thought I'd make an issue about it.
Running Waterfall 1.16 build 389. (Latest at time of writing), This did not occur running on java8

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.tcpshield.tcpshield.ReflectionUtils (file:/home/container/plugins/TCPShield-2.4.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of net.tcpshield.tcpshield.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**Comment by paulzhng** [comment]
That's something we're unable to fix and is a message that can be safely ignored.
