### ISSUE TITLE
TCPShield can't tell I'm running Paper.

### ISSUE THREAD

**Issue by katekerllenevich** [TCPShield/RealIP#31]
I am running Paper 1.16.4 on my server, but whenever I start the server I get this message: 

```
[TCPShield] TCPShield not loading because ProtocolLib is not installed. Either use Paper to enable native compatibility or install ProtocolLib.
```

Please fix this.

**Comment by paulzhng** [comment]
Currently, native paper support is disabled due to various flaws in the implementation. Please install ProtocolLib

**Comment by katekerllenevich** [comment]
Ok :shrug:
