### ISSUE TITLE
Online

### ISSUE THREAD

**Issue by Ev1LOFF** [TCPShield/RealIP#35]
After installing the plugin "TCPShield" online players stopped showing on my site, how can I fix this problem? Sorry for bad english, i use google translate :)

**Comment by ghost** [comment]
This is most likely because you haven't finished your configuration. Please follow our checklist on our docs.

https://docs.tcpshield.com/troubleshooting/setup-checklist

**Comment by Ev1LOFF** [comment]
I think everything is set up correctly:
1) Blocks direct IP connections
2) I can log into the server only by domain
3) The game shows the number of players
The number of players is not displayed, only on my personal site

**Comment by ghost** [comment]
@Ev1LOFF Our discord is better suited for these conversations. Feel free to open a ticket in there and we can discuss. 

This is a hard to cover because it can be so many variables. My only tip is just make sure your implementation of the minecraft protocol is entirely accurate.
