### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by ghost** [TCPShield/RealIP#5]
Hey i have a problem with realip i use bungeecord my i have this error that appears in my logs

[WARNING] Event PlayerHandshakeEvent §rtook §c233 041 560ns§r to process for public void net.tcpshield.realip.TCPShieldBungee.onPlayerHandshake (net.md_5.bungee.api.event.PlayerHandshakeEvent)!

**Comment by papiDoxxer** [comment]
This is not an Error, This is just to inform you that the Bungeecord has connected with the TCPShield Proxy.

**Comment by nuriofernandez** [comment]
> This is not an Error, This is just to inform you that the Bungeecord has connected with the TCPShield Proxy.

No, it's a warning about a possible performance issue during the PlayerHandshakeEvent process. That event manages display information at the Minecraft server list.

**Comment by paulzhng** [comment]
Fixed by 2ca823411fd9db033929c4826cbe7739bbca5f29
