### ISSUE TITLE
Sync Player Counts Across Multiple Bungee Instances?

### ISSUE THREAD

**Issue by kolakz** [TCPShield/RealIP#51]
Hello, I was wondering if it would be possible to sync player counts across multiple bungeecord instances with TCP Shield.

**Comment by trev-sharp** [comment]
Ping information is untouched when relayed back to the user. So if you use a plugin to do this on the proxies, and it properly sets the player information in the Ping packet, then it should work.

**Comment by kolakz** [comment]
> Ping information is untouched when relayed back to the user. So if you use a plugin to do this on the proxies, and it properly sets the player information in the Ping packet, then it should work.

Do you know any plugin that does this?

**Comment by iFlyinq** [comment]
> > Ping information is untouched when relayed back to the user. So if you use a plugin to do this on the proxies, and it properly sets the player information in the Ping packet, then it should work.
> 
> Do you know any plugin that does this?

[RedisBungee ](https://www.spigotmc.org/resources/redisbungee.13494/) @KolakZ

**Comment by kolakz** [comment]
It's not updated.

**Comment by iFlyinq** [comment]
But it does work as how it's supposed to? It doesn't require updates 🤷‍♀️

**Comment by frkri** [comment]
> It's not updated.

There is a fork of it, that is being still updated
Also Multi Bungee Setup is a very hard topic to research about

https://github.com/RedisMC/RedisBungee

**Comment by DylanKeir** [comment]
This doesn't seem to be a TCPShield related issue, therefore I'll close it.
