### ISSUE TITLE
Velocity Forced Hosts Ping Passthrough

### ISSUE THREAD

**Issue by AzraAnimating** [TCPShield/RealIP#52]
Ping Passthrough does not work Correctly on Velocity.
Server list just shows default Ping result.

Steps to reproduce:

- Set upVelocity
- Set a Default MOTD
- Set up Backend Server
- Set a different MOTD
- Setup Velocity so Ping Passthrough is set to "all"
- Only see the default MOTD

**Comment by DylanKeir** [comment]
Hi there, could you re-try this with the latest TCPShield release & with TCPShield removed to make sure this is related to us?

**Comment by CybrHare** [comment]
> Hi there, could you re-try this with the latest TCPShield release & with TCPShield removed to make sure this is related to us?

I don't know about the original issue but I just installed the latest version on Velocity 3.0.1 and the server is not accessible at all. Remote or locally. It is fully accessible without the plugin.

Edit: Though I do see that the latest version of Velocity is not marked as supported.

**Comment by BlackBeltPanda** [comment]
Can confirm this happens with TCPShield 2.5.6 on Velocity 3.0.1. Only the default MOTD is visible; the backend MOTDs are not. Applies to the server icons, as well. Example with multiple backend servers, each with their own MOTD and icon: 
![image](https://user-images.githubusercontent.com/5866087/143785061-b39956c5-abaf-4946-b684-8027c6f2b8fa.png)

**Comment by Donty10** [comment]
I realise this is an old post, but was there ever a solution to this? I'm still having the same issue.

**Comment by DylanKeir** [comment]
> I realise this is an old post, but was there ever a solution to this? I'm still having the same issue.

Yes there is a solution, join our discord and make a ticket @ discord.gg/tcpshield and we can fix this for you.
