### ISSUE TITLE
Some console errors?

### ISSUE THREAD

**Issue by download042** [TCPShield/RealIP#53]
Hi!

I just noticed some TCP shield errors in my console. 
The plugin works fine. After installed, no more bot attacks.
The founded error: https://pastebin.com/p9wCsUv1
Spigot 1.16.5, no bungee

**Comment by UserDerezzed** [comment]
Also having this issue.

**Comment by trev-sharp** [comment]
We isolated an issue with Paper implementations that should be fixed now, so if that was relating to your issue, I highly recommend updating. However, if you aren't experience issues with that and only want the warnings to go away, you will need to turn `debug` mode off under your config.

**Comment by DylanKeir** [comment]
If this is still an issue, please open a ticket at https://discord.gg/tcpshield
