### ISSUE TITLE
Broken with Velocity

### ISSUE THREAD

**Issue by greysilly7** [TCPShield/RealIP#54]
Velocity Version: 1.1.8
MC Server Version: Yatopia 1.16.5 Build 118
Steps to reproduce:
setup velocity
put tcpsheild jar in plugins

problem: cant connect to server

**Comment by Boxiogral** [comment]
Also can't connect, but when i disable only-allow-proxy-connections it works, here's debug info: 
![imagen](https://user-images.githubusercontent.com/82053174/121320041-16d8d900-c90d-11eb-9e53-80c1634a574a.png)

**Comment by greysilly7** [comment]
> Also can't connect, but when i disable only-allow-proxy-connections it works, here's debug info:
> ![imagen](https://user-images.githubusercontent.com/82053174/121320041-16d8d900-c90d-11eb-9e53-80c1634a574a.png)

Can confirm that disabling ``only-allow-proxy-connections`` works

**Comment by UserDerezzed** [comment]
I'm having the same problem.

Running Velocity 1.1.8
Purpur (Paper fork) 1.16.5 #1163
TCPShield 2.5

**Comment by greysilly7** [comment]
Should also add my backend servers used yatopia 1.16.5 build 118

**Comment by AoElite** [comment]
@greysilly7 @relavis I've made some slight changes on my [fork](https://github.com/AoElite/RealIP/tree/java16fix) that may fix this issue for you. Try using [this](https://mega.nz/file/lWpQlDrC#PwftbuXKaDD9KKhpgomXrXe-Jz7iabXxJrI0cNAGOn4) build. Also I recommend using Java 16 but as long as you are using at least Java 11 I think it should work. If it doesn't work just tell me what Java version and I'll try to fix it.

**Comment by UserDerezzed** [comment]
> @greysilly7 @relavis I've made some slight changes on my [fork](https://github.com/AoElite/RealIP/tree/java16fix) that may fix this issue for you. Try using [this](https://mega.nz/file/lWpQlDrC#PwftbuXKaDD9KKhpgomXrXe-Jz7iabXxJrI0cNAGOn4) build. Also I recommend using Java 16 but as long as you are using at least Java 11 I think it should work. If it doesn't work just tell me what Java version and I'll try to fix it.

Using Java 16 and still experiencing the same errors. Thanks for checking it out though, hopefully a fix can be found.

**Comment by louboecker** [comment]
@AoElite For me your Fork worked! Thank you!

**Comment by trev-sharp** [comment]
Anyone experiencing an issue relating to this should update to the latest build. The latest build requires you use at least `Java 11` as well.
