### ISSUE TITLE
Broken with Floodgate 2.0 and Geyser

### ISSUE THREAD

**Issue by dig** [TCPShield/RealIP#55]
Does not allow Bedrock players to connect when you update to Floodgate 2.0. Even with the geyser IPs whitelisted, still disconnects them on join. Works fine with Floodgate 1.0.

**Comment by DylanKeir** [comment]
Hi there, this should be fixed with the 2.5.4 update, please give that a go. If you still have issues please make a ticket at https://discord.gg/tcpshield and we'll help you with this.
