### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by haha44444** [TCPShield/RealIP#61]
Some errors.
Please check here: https://paste.ubuntu.com/p/X4VnT6RbKn/
I use WaterFall and ver is waterfall-1.16-431
plugins: BotSentry, DynamicSlot, ServerListPlus, ServerNameChanger, TCPShield, UltimateAntibot
You can find them in spigotmc and Github.

**Comment by trev-sharp** [comment]
Looks like your server is failing to connect to Google's servers so TCPShield can offset the time verification delay. I would suggest, for now, to go under your config and change `timestamp-validation` to `system`. However, I would look into other underlying causes to why you can't connect to the timestamp server. (Maybe firewalls, or request blocking by Google themselves)

**Comment by haha44444** [comment]
> Looks like your server is failing to connect to Google's servers so TCPShield can offset the time verification delay. I would suggest, for now, to go under your config and change `timestamp-validation` to `system`. However, I would look into other underlying causes to why you can't connect to the timestamp server. (Maybe firewalls, or request blocking by Google themselves)

Thank you. Yes, my country can't connect to the Google server, because my country blocks all Google services. I will change the " timestamp-validation" to "system". It is recommended that you write this item into the plug-in configuration. It seems that the plug-in configuration on the official website config seems to be old.

![image](https://user-images.githubusercontent.com/60396495/125457617-b06ee9ce-33db-4007-b990-56ce383f8606.png)

**Comment by DylanKeir** [comment]
> > Looks like your server is failing to connect to Google's servers so TCPShield can offset the time verification delay. I would suggest, for now, to go under your config and change `timestamp-validation` to `system`. However, I would look into other underlying causes to why you can't connect to the timestamp server. (Maybe firewalls, or request blocking by Google themselves)
> 
> Thank you. Yes, my country can't connect to the Google server, because my country blocks all Google services. I will change the " timestamp-validation" to "system". It is recommended that you write this item into the plug-in configuration. It seems that the plug-in configuration on the official website config seems to be old.
> 
> ![image](https://user-images.githubusercontent.com/60396495/125457617-b06ee9ce-33db-4007-b990-56ce383f8606.png)

I've edited the TCPShield documentation to include some information about timestamp validation.
