### ISSUE TITLE
Tcpshield stopped working..

### ISSUE THREAD

**Issue by alixplayz** [TCPShield/RealIP#70]
I used to run a minecraft server network on bungeecord and tcpshield on my normal desktop computer and it worked amazingly (set it up first try no problem).
Now I've transferred all the server files to a dedicated server (in my house) and tcp shield has stopped working.
And yes I've reconfigured all the port forwards and the config files for bungeecord and all the other paper servers. It just says "Disconnected" every time I try to join the server from my Minecraft client.

Everything works fine when I disable TCPShield too.

Thanks - Alex

**Comment by alixplayz** [comment]
bump

**Comment by szferguson** [comment]
Did you update your backend IP on the panel? Please open a ticket here https://discord.gg/tcpshield
