### ISSUE TITLE
Issue with latest velocity

### ISSUE THREAD

**Issue by WarnDa** [TCPShield/RealIP#74]
I tried to update to latest velocity 3.0.1 to get 1.18 support, but I got an error :
https://pastebin.com/iSYxpZzi

- Using TcpShield 2.5.4
- Tried java 16/17

No issue on velocity 3.0.0

**Comment by DylanKeir** [comment]
The latest build of RealIP fixes this.

https://github.com/TCPShield/RealIP/releases/tag/2.5.5
