### ISSUE TITLE
Version of forge?

### ISSUE THREAD

**Issue by luisbaker** [TCPShield/RealIP#81]
Could you release a compatible version with forge

**Comment by RegressiaUK** [comment]
I also agree we need forge, most users whom play mod pack use pure forge and the forge/bucket servers are badly coded and don't work right so please release a version for forge and this user was left without a reply since Apr please reply to them even if it's a no.

**Comment by DylanKeir** [comment]
We're already compatible with Forge if you use Proxy Protocol instead of this plugin. No plans to support sponge/forge directly with this plugin at the moment since it's unnecessary, not even required for protection, it just supplies IPs.
